### ISSUE TITLE
v1 compilation requirements

### ISSUE THREAD

**Issue by dachary** [latchset/tang#13]
Hi,

I tried to compile v1 and master as of 2f1142ca4b752158eb47f1aa3200d83c9da6a968 and both failed with 
<pre>
make
Making all in src
make[1]: Entering directory '/home/loic/software/tang/tang/src'
  CC       tangd-io.o
io.c:74:1: error: redefinition of ‘json_decrefp’
 json_decrefp(json_t **json)
 ^
In file included from io.h:22:0,
                 from io.c:20:
/usr/local/include/jansson.h:117:6: note: previous definition of ‘json_decrefp’ was here
 void json_decrefp(json_t **json)
      ^
Makefile:561: recipe for target 'tangd-io.o' failed
make[1]: *** [tangd-io.o] Error 1
make[1]: Leaving directory '/home/loic/software/tang/tang/src'
Makefile:703: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
</pre>

I compiled the dependencies using:

* https://github.com/nodejs/http-parser commit feae95a3a69f111bc1897b9048d9acbc290992f9 (HEAD -> master, tag: v2.7.1, origin/master, origin/HEAD)
* https://github.com/akheron/jansson commit 98be7da3e2cc256e16d3c9f76b3a0053a930eb2c (HEAD -> master, origin/master, origin/HEAD)
* https://github.com/latchset/jose commit e143d087d3ade6e03bcfc9b1b1549d26b654065b (HEAD -> master, origin/master, origin/HEAD)

I guess it would be better to use a jansson release instead of master (2.7 maybe ?) but jose requires 2.9 which is only provided with master. Or maybe I should use a [jose release](https://github.com/latchset/jose/releases) but I'm not sure which one.

Any hint to resolve that properly would be much appreciated. If there exists packages for those in any distribution it would also be a good way to figure out the right set of dependencies.

Thanks !

**Comment by dachary** [comment]
@npmccallum any suggestion ?

**Comment by npmccallum** [comment]
@dachary Please try git master. The requirements are all properly defined there.

**Comment by dachary** [comment]
Where ?

**Comment by npmccallum** [comment]
I meant that they weren't properly defined before. Now, configure should pick them up properly.

**Comment by dachary** [comment]
In master (as of today), the README.md states
<pre>
Tang requires a few other software libraries:

1. http-parser - https://github.com/nodejs/http-parser
2. systemd - https://github.com/systemd/systemd
3. jose - https://github.com/latchset/jose

</pre>
and when I try to
<pre>
$ autoreconf -fi
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
configure.ac:4: installing './compile'
configure.ac:7: installing './missing'
Makefile.am: installing './depcomp'
$ ./configure
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for gcc option to accept ISO C99... none needed
checking for a sed that does not truncate output... /bin/sed
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether make supports nested variables... (cached) yes
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1635000
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.25... yes
checking for dlopen in -ldl... yes
checking http_parser.h usability... yes
checking http_parser.h presence... yes
checking for http_parser.h... yes
checking for http_parser_execute in -lhttp_parser... yes
checking for jose_zlib... no
configure: error: Package requirements (jose-zlib >= 5) were not met:

Requested 'jose-zlib >= 5' but version of José zLib Library is 4

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables jose_zlib_CFLAGS
and jose_zlib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
</pre>

Since it does not provide details regarding which branch / commit to pull, I tried various combinations and ran into various problems as you can imagine ;-) Reason why I thought trying v1 would be an easier path.

Am I missing something ?

**Comment by npmccallum** [comment]
The error message tells you precisely what you need:

    Requested 'jose-zlib >= 5' but version of José zLib Library is 4

You need jose version 5 but you only have version 4.

**Comment by npmccallum** [comment]
FYI: http://koji.fedoraproject.org/koji/packageinfo?packageID=23093

**Comment by dachary** [comment]
Two weeks ago I got the same message but v5 was not there yet:
<pre>
(virtualenv) loic@fold:~/software/tang/jose$ git tag -l
v1
v2
v3
v4
</pre>
so I compiled from master and that worked but I got stuck later. 
<pre>
(virtualenv) loic@fold:~/software/tang/jose$ git fetch
remote: Counting objects: 74, done.
remote: Total 74 (delta 55), reused 55 (delta 55), pack-reused 19
Unpacking objects: 100% (74/74), done.
From https://github.com/latchset/jose
   e143d08..ca20c07  master     -> origin/master
 * [new tag]         v5         -> v5
</pre>
Cool, I'll try with v5 now, assuming I'll get the same as what is packaged at http://koji.fedoraproject.org/koji/packageinfo?packageID=23093 (not running fedora).

To be continued :-)

**Comment by dachary** [comment]
It compiles ok !
