### ISSUE TITLE
Why is tangd@.service a templated unit?

### ISSUE THREAD

**Issue by opoplawski** [latchset/tang#25]
Why is tangd@.service a templated unit?  It does not use %i anywhere.  Can you run multiple tangd processes?

**Comment by npmccallum** [comment]
Currently, tang runs one process per connection. This could be improved. The templated unit is an artefact of socket activation. Patches to improve this are welcome.

**Comment by opoplawski** [comment]
Ah, my bad.  I didn't realize that the unit needed to be a template when using Accept=true.
