### ISSUE TITLE
Is tang tied to systemd to operate?

### ISSUE THREAD

**Issue by nexfwall** [latchset/tang#33]
I wanted to create a package for a OpenWRT, so I can set it up on a router. But I see there is some systemd staff used, like socket activation. Well, I have nothing against systemd, but OpenWRT does.

Can tang be used without systemd?

**Comment by npmccallum** [comment]
Yes, it can! https://github.com/openwrt/packages/pull/5447

**Comment by nexfwall** [comment]
Thank you.
