### ISSUE TITLE
meson.build missing from root directory, doc, src, units, and tests

### ISSUE THREAD

**Issue by ola-pt** [latchset/tang#59]
If a user downloads the latest tag: https://github.com/latchset/tang/releases/tag/v7

The install will not include the needed meson.build files if they are trying to install from source

**Comment by hdholm** [comment]
The meson build system wasn't added until commit fed902018e218410cff5231cfae47b8f8e72bda3 which is after the v7 tag/release.  It looks like all the appropriate autoconf stuff is in V7.

**Comment by ola-pt** [comment]
Thanks for letting me know; I'll close this issue out now
